apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api-deployment
  labels:
    app: hello-world-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      name: hello-world-api
      labels:
        app: hello-world-api
        tier: backend
    spec:
      containers:
        - name: hello-world-api
          image: bakeruk/hello-world-api
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
